# Copyright 2022 The KubeVela Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG BUILD_IMAGE=golang:1.17
ARG BASE_IMAGE=gcr.io/distroless/static:nonroot

# Force native build platform, and cross-build to target platform later.
FROM --platform=${BUILDPLATFORM:-linux/amd64} ${BUILD_IMAGE} as builder

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum

ARG GOPROXY
ENV GOPROXY=${GOPROXY}
RUN go mod download

COPY build       build
COPY hack        hack
COPY cmd         cmd
COPY api         api
COPY controllers controllers
COPY pkg         pkg

ARG TARGETARCH
ARG ARCH
# TARGETARCH in Docker BuildKit have higher priority.
ENV ARCH=${TARGETARCH:-${ARCH:-amd64}}
ARG TARGETOS
ARG OS
# TARGETOS in Docker BuildKit have higher priority.
ENV OS=${TARGETOS:-${OS:-linux}}
ARG VERSION
ENV VERSION=${VERSION}
ARG GOFLAGS
ENV GOFLAGS=${GOFLAGS}
ARG ENTRY

RUN ARCH=${ARCH}               \
        OS=${OS}               \
        OUTPUT=${BIN}          \
        VERSION=${VERSION}     \
        GOFLAGS=${GOFLAGS}     \
        /bin/sh build/build.sh \
        ${ENTRY}

FROM ${BASE_IMAGE}
WORKDIR /

# This ${BIN} needs to be replace with the actual binary,
# otherwise it won't work. Refer to Makefile for how it works.
COPY --from=builder /workspace/${BIN} .
ENTRYPOINT ["/${BIN}"]
