# Copyright 2022 The KubeVela Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Note: the ${BIN} needs to be replaced with the actual binary,
# otherwise it won't work. A valid Dockerfile will be generated
# using this template. Refer to Makefile for how it can be done.

# Default value is specified and will be overridden by the one in Makefile
ARG BASE_IMAGE=gcr.io/distroless/static:nonroot

FROM ${BASE_IMAGE}

WORKDIR /

ARG TARGETARCH
ARG ARCH
ARG TARGETOS
ARG OS
ARG VERSION

COPY ${BIN}-${VERSION}-${TARGETOS:-${OS:-linux}}-${TARGETARCH:-${ARCH:-amd64}} /${BIN}

ENTRYPOINT ["/${BIN}"]
