#!/usr/bin/env bash

# Copyright 2022 The KubeVela Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

if [[ $# -ne 1 ]]; then
    echo "need one argument as CUE file input" >&2
    exit 1
fi

CUE_FILE=$1

if [ -z "${CUE_FILE:-}" ]; then
  echo "missing cue file" >&2
  exit 1
fi

# Append a \n at the end to allow direct concatenation
CUE_CONTENT="$(cat "${CUE_FILE}")\n"

PACKAGE_NAME="$(basename "${PWD}")"

SCRIPT_DIR="$(dirname "${BASH_SOURCE}")"
BOILERPLATE="$(cat "${SCRIPT_DIR}"/boilerplate/boilerplate.go.txt)"
YEAR="$(date +"%Y")"

echo -e "//go:build !ignore_autogenerated\n\n\
${BOILERPLATE/YEAR/${YEAR}}\n\n\
// Code generated by generate-properties-const-from-cue.sh. DO NOT EDIT.\n\n\
// Instead, edit ${CUE_FILE} and regenerate this using go generate ./...\n
package ${PACKAGE_NAME}\n
const propertiesCUETemplate = \`${CUE_CONTENT}\`" \
> "zz_generated.properties.go"
