#!/usr/bin/env bash

# Copyright 2022 The KubeVela Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script generates a go const from contents from a file.

set -o errexit
set -o nounset
set -o pipefail

if [[ $# -ne 3 ]]; then
    echo "need arguments: file input, const name, zz_generated.xxxname.go" >&2
    exit 1
fi

FILE=$1
CONST_NAME=$2

GENERATED_FILENAME="zz_generated.$3.go"

# Append a \n at the end to allow direct concatenation
FILE_CONTENT="$(cat "${FILE}")\n"

PACKAGE_NAME="$(basename "${PWD}")"

SCRIPT_DIR="$(dirname "${BASH_SOURCE}")"
BOILERPLATE="$(cat "${SCRIPT_DIR}"/boilerplate/boilerplate.generatego.txt)"
YEAR="$(date +"%Y")"

echo "Generating ${PWD}/${GENERATED_FILENAME} from ${FILE}"

# TODO: make ` can appear in FILE_CONTENT as well. Currently, it can not.
echo -e "//go:build !ignore_autogenerated\n\n\
${BOILERPLATE}\n\n\
// Code generated by "${BASH_SOURCE}". DO NOT EDIT.\n\n\
// Instead, edit ${FILE} and regenerate this using go generate ./...\n
package ${PACKAGE_NAME}\n
const ${CONST_NAME} = \`${FILE_CONTENT}\`" \
> "${GENERATED_FILENAME}"
