apiVersion: standard.oam.dev/v1alpha1
kind: TriggerService
metadata:
  name: watch-workflowrun
  namespace: default
spec:
  triggers:
    - source:
        type: resource-watcher
        properties:
          apiVersion: core.oam.dev/v1alpha1
          kind: WorkflowRun
          events:
            - create
          matchingLabels:
            trigger.oam.dev/watch: "true"
      filter: ""
      action:
        type: create-event-listener

