apiVersion: standard.oam.dev/v1alpha1
kind: TriggerService
metadata:
  name: image-rebase-trigger
  namespace: default
spec:
  triggers:
    - source:
        # source is all the kpack Image resources in all the namespaces
        type: resource-watcher
        properties:
          apiVersion: kpack.io/v1alpha2
          # kpack needs to be installed on the cluster to have this resource type
          kind: Image
          events:
            - update

      # only trigger action when an Image is successfully rebased
      filter: >
        context.data.status.latestBuildReason == "STACK" && context.data.status.conditions[0].status == "True"
      
      action:
        type: task
        properties:
          cmd: [/bin/sh, -c, "echo Image: ${SOURCE_NAME} in namespace: ${SOURCE_NAMESPACE} has been successfully rebased at $(date)"]
          image: busybox
          name: image-update-task
          ttlSecondsAfterFinished: 600
