apiVersion: standard.oam.dev/v1alpha1
kind: TriggerService
metadata:
  name: kubetrigger-sample-config
  namespace: default
spec:
  # A trigger is a group of Source, Filters, and Actions.
  # You can add multiple triggers.
  triggers:
    - source:
        type: resource-watcher
        properties:
          # We are interested in ConfigMap events.
          apiVersion: "v1"
          kind: ConfigMap
          namespace: default
          # Only watch update event.
          events:
            - update
      filter: |
        context: data: metadata: name: =~"this-will-trigger-update-.*"
      action:
        # Bump Application Revision to update Application.
        type: bump-application-revision
        properties:
          namespace: default
          # Select Applications to bump using labels.
          matchingLabels:
            my-label: my-value
