//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright  The KubeVela Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	"github.com/kubevela/kube-trigger/pkg/action/builtin/bumpapplicationrevision"
	"github.com/kubevela/kube-trigger/pkg/action/builtin/patchk8sobjects"
	"github.com/kubevela/kube-trigger/pkg/filter/builtin/cuevalidator"
	k8sresourcewatcherconfig "github.com/kubevela/kube-trigger/pkg/source/builtin/k8sresourcewatcher/config"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionMetaWrapper) DeepCopyInto(out *ActionMetaWrapper) {
	*out = *in
	if in.BumpApplicationRevision != nil {
		in, out := &in.BumpApplicationRevision, &out.BumpApplicationRevision
		*out = new(bumpapplicationrevision.Properties)
		(*in).DeepCopyInto(*out)
	}
	if in.PatchK8sObjects != nil {
		in, out := &in.PatchK8sObjects, &out.PatchK8sObjects
		*out = new(patchk8sobjects.Properties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionMetaWrapper.
func (in *ActionMetaWrapper) DeepCopy() *ActionMetaWrapper {
	if in == nil {
		return nil
	}
	out := new(ActionMetaWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterMetaWrapper) DeepCopyInto(out *FilterMetaWrapper) {
	*out = *in
	if in.CUEValidator != nil {
		in, out := &in.CUEValidator, &out.CUEValidator
		*out = new(cuevalidator.Properties)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterMetaWrapper.
func (in *FilterMetaWrapper) DeepCopy() *FilterMetaWrapper {
	if in == nil {
		return nil
	}
	out := new(FilterMetaWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceMetaWrapper) DeepCopyInto(out *SourceMetaWrapper) {
	*out = *in
	if in.K8sResourceWatcher != nil {
		in, out := &in.K8sResourceWatcher, &out.K8sResourceWatcher
		*out = new(k8sresourcewatcherconfig.Properties)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceMetaWrapper.
func (in *SourceMetaWrapper) DeepCopy() *SourceMetaWrapper {
	if in == nil {
		return nil
	}
	out := new(SourceMetaWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerMetaWrapper) DeepCopyInto(out *TriggerMetaWrapper) {
	*out = *in
	in.SourceMetaWrapper.DeepCopyInto(&out.SourceMetaWrapper)
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]FilterMetaWrapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ActionMetaWrapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerMetaWrapper.
func (in *TriggerMetaWrapper) DeepCopy() *TriggerMetaWrapper {
	if in == nil {
		return nil
	}
	out := new(TriggerMetaWrapper)
	in.DeepCopyInto(out)
	return out
}
