name: Docs Checks

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch: { }

jobs:
  checks:
    name: Check Docs
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check boilerplate
        run: make checklicense

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23
          cache: true

      # Currently not required
      # Will be required to auto-gen docs in the future
      - name: Run Go Generate
        run: make generate

      - name: Check SVG formatting
        run: LINT=true make svgformat